name: Gestao de vagas application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: "maven"

      - name: Build project
        
        run: mvn clean install -DskipTests

      - name: Login docker
        if: success()
        uses: docker/login-action@v3 # Forma mais segura e recomendada
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        if: success()
        run: docker build -t gsromualdo/gestao_vagas .

      - name: Publish image
        if: success()
        run: docker push gsromualdo/gestao_vagas

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: target/surefire-reports/

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image docker hub
        # Corrigido: Removido o "docker push" do meio do comando
        run: docker pull gsromualdo/gestao_vagas:latest

      - name: Remove old container
        # O "|| true" serve para o deploy não quebrar se o container não existir ainda
        run: docker rm -f gestao-vagas || true

      - name: Run docker container gestao-vagas
        # Corrigido: Ajustado o hífen antes de DATABASE_USERNAME e sintaxe das variáveis
        run: |
          docker run -d -p 8080:8080 \
          -e DATABASE_URL='${{secrets.DATABASE_URL}}' \
          -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' \
          -e DATABASE_USERNAME='${{secrets.DATABASE_USERNAME}}' \
          --name gestao-vagas gsromualdo/gestao_vagas:latest